name: flutter_share_example
description: Demonstrates how to use the flutter_share plugin.

publish_to: none

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  screenshot: ^3.0.0
  file_picker: ^8.0.0+1
  path_provider: ^2.0.1

  flutter_share:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'